apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red
          ports:
            - containerPort: 1880
          livenessProbe:
            httpGet:
              path: /
              port: 1880
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
